name: Conditional Workflow

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Running main job"
      - name: Force failure for testing
        run: exit 1

  fallback:
    name: Fallback Job
    needs: main
    if: failure()  # Solo se ejecuta si main falla
    runs-on: ubuntu-latest
    steps:
      - name: Dummy fallback step
        run: echo "Running fallback job"
        # Simula fallo con: exit 1

  finalize:
    name: Finalize Job
    needs:
      - main
      - fallback
    # Ejecutar solo si al menos uno tuvo éxito
    if: |
      (needs.main.result == 'success') || 
      (needs.main.result == 'failure' && needs.fallback.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Final success case
        run: echo "Workflow completed successfully 🎉"

  finalize_fail:
    name: Finalize Failure Case
    needs:
      - main
      - fallback
    if: |
      (needs.main.result == 'failure') && 
      (needs.fallback.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Final failure case
        run: |
          echo "Workflow failed ❌"
          exit 1
