name: Workflow robusto con fallback

on:
  workflow_dispatch:

jobs:
  primer-job:
    name: Primer intento
    runs-on: ubuntu-latest
    timeout-minutes: 0.5
    continue-on-error: true
    steps:
      - name: Tarea que puede hacer timeout
        run: |
          echo "Simulando trabajo largo..."
          sleep 70

  evaluar:
    name: Evaluar necesidad de fallback
    runs-on: ubuntu-latest
    needs: primer-job
    outputs:
      usar_fallback: ${{ steps.decision.outputs.fallback }}
    steps:
      - name: Decidir si se activa fallback
        id: decision
        run: |
          if [[ "${{ needs.primer-job.result }}" == "success" ]]; then
            echo "fallback=no" >> $GITHUB_OUTPUT
          else
            echo "fallback=si" >> $GITHUB_OUTPUT
          fi

  fallback:
    name: Job de Fallback
    runs-on: ubuntu-latest
    needs: evaluar
    if: needs.evaluar.outputs.usar_fallback == 'si'
    steps:
      - name: Ejecutar fallback
        run: echo "🔥 Ejecutando fallback porque el primer job falló o fue cancelado (timeout)"
