name: CI Detect Fail

on:
  workflow_dispatch:

jobs:
  primer-job:
    runs-on: ubuntu-latest
    continue-on-error: true  # Permite que el job contin칰e si falla un step
    outputs:
      resultado: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Comando que falla
        id: test
        run: |
          echo "Ejecutando algo que fallar치..."
          exit 1
        continue-on-error: true  # 游녣 Permite que falle sin cortar el job

      - name: Evaluar si el paso fall칩 y emitir output
        id: set-output
        run: |
          if [[ "${{ steps.test.outcome }}" == "failure" ]]; then
            echo "status=FAIL" >> $GITHUB_OUTPUT
          else
            echo "status=OK" >> $GITHUB_OUTPUT
          fi

  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    if: needs.primer-job.outputs.resultado == 'FAIL'
    steps:
      - name: Ejecutar solo si primer-job fall칩
        run: echo "Se detect칩 un fallo en el primer job"
