name: Conditional Workflow

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Main Job
    runs-on: ubuntu-latest
    outputs:
      main_status: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Dummy main logic with controlled failure
        id: run-main
        run: |
          echo "Running main job..."
          false  # <- simula un fallo real
          echo $? > main_status.txt

      - name: Capture status (simulate logic handling)
        id: set-output
        run: |
          if [ -f main_status.txt ]; then
            STATUS=$(cat main_status.txt)
          else
            STATUS=1
          fi
          echo "Main status is $STATUS"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"
        continue-on-error: true  # Nunca falla el job realmente

  fallback:
    name: Fallback Job
    needs: main
    if: ${{ needs.main.outputs.main_status != '0' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dummy fallback step
        run: |
          echo "Running fallback logic to recover from main failure"
          # Simula que el fallback tuvo éxito
          exit 0

  finalize_fail:
      name: Finalize Failure
      needs:
        - main
        - fallback
      if: |
        always() &&
        needs.main.outputs.main_status != '0' &&
        failure()
      runs-on: ubuntu-latest
      steps:
        - name: Final error report
          run: |
            echo "❌ Workflow failed completely."
            exit 1
