# This is a basic workflow to help you get started with Actions

name: CI Test 2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  primer-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Esto falla
        run: exit 1

  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    steps:
      - name: Esto se ejecuta aunque el anterior falló
        run: echo "Todo bien aquí"
