name: CI Detect Fail

on:
  workflow_dispatch:

jobs:
  primer-job:
    runs-on: ubuntu-latest
    continue-on-error: true  # 👈 importante: permite fallar sin bloquear outputs
    outputs:
      resultado: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Ejecutar y capturar fallo
        id: test
        run: |
          echo "Ejecutando..."
          exit 1
        continue-on-error: true

      - name: Guardar output
        id: set-output
        run: |
          if [[ "${{ steps.test.outcome }}" == "failure" ]]; then
            echo "status=FAIL" >> $GITHUB_OUTPUT
          else
            echo "status=OK" >> $GITHUB_OUTPUT
          fi

  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    if: needs.primer-job.outputs.resultado == 'FAIL'
    steps:
      - name: Ejecutar solo si primer-job falló
        run: echo "Se detectó un fallo en el primer job"
