# This is a basic workflow to help you get started with Actions

name: CI Test 2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Comando que puede fallar
        run: exit 1

  recovery-job:
    runs-on: windows-latest
    needs: main-job
    if: failure()  # Solo se ejecuta si el anterior falló
    steps:
      - run: echo "Ejecutando recuperación en Windows"
