# This is a basic workflow to help you get started with Actions

name: CI Test 2

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  primer-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Esto falla
        run: exit 1

  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    steps:
      - name: Esto se ejecuta aunque el anterior falló
        run: exit 1
