name: Create PR from upstream to master

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Smart Runner Selection"]
    types: [completed]

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch upstream branch
        run: git fetch origin upstream:upstream --depth=1

      - name: Verificar rama
        id: check-branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/upstream; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Crear Pull Request
        if: steps.check-branch.outputs.exists == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Actualización desde upstream"
          body: "Pull Request automático para incorporar cambios desde la rama upstream a master"
          base: master
          branch: "sync-upstream-to-master"
          branch-suffix: timestamp
          commit-message: "Sincronizar cambios desde upstream"
          labels: "automated-pr"
          delete-branch: true
