name: Sync Upstream to Main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote -v
          git branch -a

      - name: Fetch and compare branches
        id: compare
        run: |
          git fetch origin upstream
          
          # Create temporary branch from upstream
          git checkout -b temp-upstream upstream
          
          # Count commits difference
          COMMIT_COUNT=$(git rev-list --count main..temp-upstream)
          if [ "$COMMIT_COUNT" -gt 0 ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
            echo "::notice::Found $COMMIT_COUNT new commits"
            git log --oneline main..temp-upstream
          else
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi
          
          # Clean up
          git checkout main
          git branch -D temp-upstream

      - name: Create Pull Request (v6 compatible)
        if: steps.compare.outputs.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync: Upstream → Main [Automated]"
          body: "Automated update from upstream branch"
          base: main
          branch: "sync-upstream-to-main-$(date +%s)"
          commit-message: "chore: sync changes from upstream"
          labels: "automated-pr"
          delete-branch: true

      - name: Show result
        run: |
          if [ "${{ steps.compare.outputs.changes_exist }}" == "true" ]; then
            echo "PR created successfully"
          else
            echo "No changes to sync between upstream and main"
          fi
