name: Create PR from upstream to master

on:
  workflow_dispatch: # permite correrlo manualmente desde GitHub
  schedule:
    - cron: '0 12 * * 1' # cada lunes a las 12:00 UTC (ajústalo según lo necesites)

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync upstream into master'
          title: 'Merge upstream into master'
          body: |
            This PR merges changes from the `upstream` branch into `master`.
            Please review and merge if appropriate.
          base: master
          head: upstream
          branch: auto/upstream-to-master
          delete-branch: true
          draft: false
