name: Fallback on Failure

on:
  # Ejecutar automáticamente si "Main Workflow" falla
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

  # También permitir ejecución manual
  workflow_dispatch:

jobs:
  run-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fallback ejecutado
        run: echo "🚨 El workflow 'Main Workflow' falló. Ejecutando fallback."
